version: "3"
services:
  receiver:
    image: msendera/tip_receiver
    command: mitmdump -s receiver.py -p 5001 -R http://localhost:8000
    ports:
      - "5001:5001"
    volumes:
      - ./:/home/receiver
