version: "3"
services:
  receiver:
    image: roxel/tip_receiver
    command: sh
    ports:
      - "5001:5001"
    networks:
      - sender_tip_project

networks:
  sender_tip_project:
    external: true