version: "3"
services:
  receiver:
    image: tip_receiver
    command: mitmdump -s receiver.py -p 5001 -R http://127.0.0.1:8000
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./:/home/receiver
