version: "3"
services:
  app:
    image: tip_dd
    command: python app.py
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/dd/
    networks:
      - tip_project

networks:
  tip_project:
    driver: bridge