version: "3"
services:
  sender:
    image: msendera/tip_sender
    command: python -m http.server 5000
    restart: always
    ports:
      - "5000:5000"
    networks:
      - tip_project

networks:
  tip_project:
    driver: bridge