version: "3"
services:
  sender:
    image: msendera/tip_sender
    command: mitmdump -s sender.py -p 5000 -R http://172.19.0.2:5001
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/sender/
