version: "3"
services:
  sender:
    image: tip_sender
    command: mitmdump -s sender.py -p 5000 -R http://127.0.0.1:5001
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/sender/
