version: "3"
services:
  sender:
    image: roxel/tip_sender
#    command: python sender.py
    restart: always
    ports:
      - "5000:5000"
    networks:
      - tip_project

networks:
  tip_project:
    driver: bridge