version: "3"
services:
  sender:
    image: tip_sender
    command: mitmdump -s sender.py -p 5000 -R http://172.18.0.3:5001
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/sender/
    networks:
      - demo_tip_project

networks:
  demo_tip_project:
    external: true